// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fmqwleqbkgpvmjwenvtt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZtcXdsZXFia2dwdm1qd2VudnR0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYyNDM4MTEsImV4cCI6MjA3MTgxOTgxMX0.knus84F4T02dyTmj9JDUamk5MBclCys2bDsNGCDToA0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});